/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.task_management;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author login
 */
public class AddEmployee extends javax.swing.JFrame {

    String ch= new String();
    boolean isUpdate = false;
    EmployeeClass employeeData = new EmployeeClass();
    ConnectionClass con = ConnectionClass.getInstance();
    String simpleDate;

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
        btnDelete.setVisible(false);
        Date d = new Date();
        SimpleDateFormat frrmatter = new SimpleDateFormat("dd/MM/yyyy");
        simpleDate = frrmatter.format(d);

        name1.setVisible(false);
        email1.setVisible(false);
//        address1.setVisible(false);
        adhar1.setVisible(false);
        contact1.setVisible(false);
        password1.setVisible(false);
        age1.setVisible(false);
    }

    public AddEmployee(EmployeeClass employeeData) {
        initComponents();
        btnDelete.setVisible(true);
        isUpdate = true;
        btn1.setText("Update Employee");
        this.employeeData = employeeData;
        name.setText(employeeData.getName());
        address.setText(employeeData.getAddress());
        contactNumber.setText(employeeData.getContactNumber());
        emailId.setText(employeeData.getEmail());
        age.setText(String.valueOf(employeeData.getAge()));
        password.setText(employeeData.getPassword());
        adharNumber.setText(employeeData.getAdharNumber());

        name1.setVisible(false);
        email1.setVisible(false);
//        address1.setVisible(false);
        adhar1.setVisible(false);
        contact1.setVisible(false);
        password1.setVisible(false);
        age1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emailId = new javax.swing.JTextField();
        contactNumber = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        adharNumber = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        btn1 = new javax.swing.JButton();
        name1 = new javax.swing.JLabel();
        contact1 = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        age1 = new javax.swing.JLabel();
        adhar1 = new javax.swing.JLabel();
        password1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Employee");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jLabel2.setText("Name :");

        jLabel3.setText("Adhar Number:");

        jLabel4.setText("Address:");

        jLabel5.setText("Contact number:");

        jLabel6.setText("Age:");

        jLabel7.setText("Password:");

        jLabel8.setText("Email Id:");

        emailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdActionPerformed(evt);
            }
        });
        emailId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailIdKeyTyped(evt);
            }
        });

        contactNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactNumberKeyTyped(evt);
            }
        });

        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });

        adharNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adharNumberActionPerformed(evt);
            }
        });
        adharNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adharNumberKeyTyped(evt);
            }
        });

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        btnDelete.setText("Delete  Employee");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        btn1.setText("Add Employee");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        name1.setText("jLabel9");

        contact1.setText("jLabel11");

        email1.setText("jLabel13");
        email1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                email1KeyTyped(evt);
            }
        });

        age1.setText("jLabel14");

        adhar1.setText("jLabel15");

        password1.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(contact1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailId, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(email1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(adharNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(age1)
                                    .addComponent(adhar1))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(password1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(btnDelete)
                .addGap(124, 124, 124)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1)
                    .addComponent(email1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(age1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adharNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contact1)
                    .addComponent(adhar1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(877, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String sql = "DELETE FROM addemployee WHERE id=?";
            PreparedStatement preparedStatement2 = con.connection.prepareStatement(sql);
            preparedStatement2.setInt(1, employeeData.getId());
//            preparedStatement2.execute/();
            if (preparedStatement2.executeUpdate() > 0) {
                System.out.println("deleted successfully");
                JOptionPane.showMessageDialog(null, "deleted sucessfully");
//                    this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, " sorry not able to delete");

                System.out.println("Sorry don't  deleted");
            }

        } catch (SQLException ex) {
            System.out.println("exception in addEmployeer delete action " + ex);
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        EmployeeTable employee = new EmployeeTable();
        employee.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (name.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter name ");
        } else if (address.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter address ");
        } else if (emailId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter email ");
        } else if (password.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter password ");
        } else if (contactNumber.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter contact number ");
        } else if (age.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter age ");
        } else if (adharNumber.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Adhar Number ");
        } 
        else if ( !isValidEmailID(ch) ) {
                        JOptionPane.showMessageDialog(this, "Please enter valid email");

          email1.setVisible(true);
          email1.setText("please enter a valid email");
        } else {
            if (!isUpdate) {
                String sql = "INSERT INTO addemployee (name, joiningDate, age, address, email, password, contactNumber,"
                        + "adharNumber) VALUES(?,?,?,?,?,?,?,?)";
                try {
                    PreparedStatement ps = con.connection.prepareStatement(sql);
                    ps.setString(1, name.getText().trim());
                    ps.setString(2, simpleDate);
                    ps.setInt(3, Integer.parseInt(age.getText().trim()));
                    ps.setString(4, address.getText().trim());
                    ps.setString(5, emailId.getText().trim());
                    ps.setString(6, password.getText().trim());
                    ps.setString(7, contactNumber.getText().trim());
                    ps.setString(8, adharNumber.getText().trim());
                    ps.execute();
                    System.out.println("Added employee sucessfully");
                    JOptionPane.showMessageDialog(null, "added sucessfully");

                } catch (SQLException ex) {
                    Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                String str = "UPDATE addemployee SET name=?,age=?,address=?,email=?,password=?,contactNumber=?,adharnumber=? WHERE ID=?";
                try {
                    PreparedStatement ps = con.connection.prepareStatement(str);
                    ps.setString(1, name.getText().trim());
//                ps.setString(2, simpleDate);
                    ps.setInt(2, Integer.parseInt(age.getText().trim()));
                    ps.setString(3, address.getText().trim());
                    ps.setString(4, emailId.getText().trim());
                    ps.setString(5, password.getText().trim());
                    ps.setString(6, contactNumber.getText().trim());
                    ps.setString(7, adharNumber.getText().trim());
                    ps.setInt(8, employeeData.getId());
                    ps.execute();
                    JOptionPane.showMessageDialog(null, "updated sucessfully");

                    System.out.println("Updated sucessfully");

                } catch (SQLException ex) {
                    Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            EmployeeTable employee = new EmployeeTable();
            employee.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void emailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdActionPerformed

    private void adharNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adharNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adharNumberActionPerformed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        name1.setVisible(false);
        char ch = evt.getKeyChar();
        if (Character.isLetter(ch) || ch == KeyEvent.VK_SPACE || ch == KeyEvent.VK_BACK_SPACE) {
        } else {
            name1.setVisible(true);
            name1.setText("Invalid Character " + ch);
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyTyped

    private void emailIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailIdKeyTyped
        char c = evt.getKeyChar();
ch = ch+c;

        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdKeyTyped

    private void email1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email1KeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_email1KeyTyped

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        age1.setVisible(false);
        char ch = evt.getKeyChar();
        if (Character.isDigit(ch) || ch == KeyEvent.VK_BACK_SPACE) {
        } else {
            age1.setVisible(true);
            age1.setText("Invalid Character " + ch);
            evt.consume();

        }     // TODO add your handling code here:
    }//GEN-LAST:event_ageKeyTyped

    private void contactNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNumberKeyTyped
        contact1.setVisible(false);
        char ch = evt.getKeyChar();
        if (Character.isDigit(ch) || ch == KeyEvent.VK_BACK_SPACE) {
        } else {
            contact1.setVisible(true);
            contact1.setText("Invalid Character " + ch);
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberKeyTyped

    private void adharNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adharNumberKeyTyped
        adhar1.setVisible(false);
        char ch = evt.getKeyChar();
        int length = adharNumber.getText().length();

        if (Character.isDigit(ch) || ch == KeyEvent.VK_BACK_SPACE) {
            adhar1.setVisible(false);
        } else {
            adhar1.setVisible(true);
            adhar1.setText("Invalid Character " + ch);
            evt.consume();
        }
        if (length == 11) {
            System.out.println("Adhar Number valid ");
            adhar1.setForeground(new Color(0, 204, 51));
            adhar1.setText("Valid Adhar Number");
            adhar1.setVisible(true);
        } else {
            adhar1.setForeground(new Color(255, 0, 0));
            adhar1.setText("Invalid Adahr Number");
            adhar1.setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_adharNumberKeyTyped

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        password1.setVisible(false);
        char ch = evt.getKeyChar();
        int length = password.getText().length();

        if (length > 0 && length < 5) {
                password1.setVisible(true);
                password1.setText("weak password");
        }else if(length >= 5 && length <= 8){
                    password1.setVisible(true);
                                   password1.setText("average password");

        }else if( length > 8){
                    
            
                password1.setVisible(true);
                password1.setText("strong password");

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel adhar1;
    private javax.swing.JTextField adharNumber;
    private javax.swing.JTextField age;
    private javax.swing.JLabel age1;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel contact1;
    private javax.swing.JTextField contactNumber;
    private javax.swing.JLabel email1;
    private javax.swing.JTextField emailId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name1;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password1;
    // End of variables declaration//GEN-END:variables
 public boolean isValidEmailID( String email) {
     
     System.out.println(email);
        String regex = "^(.+)@(gmail.com)$";
        Pattern ptrn = Pattern.compile(regex);
        Matcher matcher = ptrn.matcher(email);
        return matcher.matches();

    }
}
