/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.task_management;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author login
 */
public class EmployeeTable extends javax.swing.JFrame {
ConnectionClass connectionClass = ConnectionClass.getInstance();
    ArrayList<EmployeeClass> employeeData = new ArrayList<>();
    int selectedRow;
    /**
     * Creates new form EmployeeTable
     */
    public EmployeeTable() {
        initComponents();
        createTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jButton1.setText("Add Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Go to Home ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            selectedRow = table.getSelectedRow();
            String i = dtm.getValueAt(selectedRow, 0).toString();
            System.out.println("ID is " + i);

            EmployeeClass data = new EmployeeClass();
            data.setId(Integer.parseInt(dtm.getValueAt(selectedRow, 0).toString()));
            data.setName(dtm.getValueAt(selectedRow, 1).toString());
            data.setEmail(dtm.getValueAt(selectedRow, 2).toString());
            data.setAge(Integer.parseInt(dtm.getValueAt(selectedRow, 3).toString()));
            data.setJoiningDate(dtm.getValueAt(selectedRow, 4).toString());

            String sql = "SELECT * FROM addemployee WHERE ID  =?";
            PreparedStatement ps = connectionClass.connection.prepareStatement(sql);
            ps.setInt(1, data.getId());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                data.setAddress(rs.getString("Address"));
                data.setPassword(rs.getString("password"));
                data.setContactNumber(rs.getString("contactNumber"));
                data.setAdharNumber(rs.getString("adharNumber"));
                
            }
            AddEmployee employee = new AddEmployee(data);
            employee.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeTable.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AddEmployee add = new AddEmployee();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AdminPanel admin = new AdminPanel();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
public void createTable() {
        String statement = "SELECT * FROM addemployee";
    try {
        PreparedStatement ps = connectionClass.connection.prepareStatement(statement);
         System.out.println("Sucess");
//                                ps.setInt(1, 1);

            ResultSet resultSet = ps.executeQuery();
            System.out.println("Sucessfullt executed");

            String[] headerName = {"ID", "Name", "emailId", "Age","Joining Date"};
            DefaultTableModel model = new DefaultTableModel(null, headerName);
            table.setModel(model);
            while (resultSet.next()) {
                EmployeeClass data = new EmployeeClass();
                data.setId(resultSet.getInt("ID"));
                data.setName(resultSet.getString("name"));
//                    data.setLastName(resultSet.getString("LastName"));
                data.setEmail(resultSet.getString("email"));
                data.setAge(resultSet.getInt("age"));
                data.setJoiningDate(resultSet.getString("joiningDate"));
//                                        data.setFullname(data.getFirstName(), data.getLastName());
//
                employeeData.add(data);
            }

            Object[] row = new Object[5];
            for (int i = 0; i < employeeData.size(); i++) {
                row[0] = employeeData.get(i).getId();
                row[1] = employeeData.get(i).getName();
                row[2] = employeeData.get(i).getEmail();
                row[3] = employeeData.get(i).getAge();
                row[4] = employeeData.get(i).getJoiningDate();
                model.addRow(row);
//                    }

            }

    } catch (SQLException ex) {
        Logger.getLogger(EmployeeTable.class.getName()).log(Level.SEVERE, null, ex);
    }

}

}
