/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.task_management;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author login
 */
public class TaskTable extends javax.swing.JFrame {
TaskClass data;
    EmployeeClass ManagerData;
    int role, selectedRow;
    ConnectionClass connectionClass = ConnectionClass.getInstance();
    ArrayList< TaskClass> taskdata = new ArrayList<>();

    /**
     * Creates new form TaskTable
     */
    public TaskTable() {
        initComponents();

    }

    public TaskTable(int role, EmployeeClass ManagerData) {
        initComponents();
        this.ManagerData = ManagerData;
        this.role = role;
//                    you.setVisible(false);
        if (role == 1) {
            createTable();
        }
        if (role == 2) {
            createTable();
//            createAssignTable();
        }
        if (role == 3) {
            createAssignTable();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new com.mycompany.task_management.TableDark();
        jPanel2 = new javax.swing.JPanel();
        button1 = new com.mycompany.task_management.Button();
        button2 = new com.mycompany.task_management.Button();
        button3 = new com.mycompany.task_management.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table);

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        button1.setForeground(new java.awt.Color(0, 153, 0));
        button1.setText("View Pending Tasks");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setForeground(new java.awt.Color(0, 153, 0));
        button2.setText("View Completed Task ");
        button2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setForeground(new java.awt.Color(0, 153, 0));
        button3.setText("Go To Home ");
        button3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
 try {
//"ID", "Title", "Description", "Start Date", "Due Date","Status"
            // TODO add your handling code here:
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            selectedRow = table.getSelectedRow();
            String i = dtm.getValueAt(selectedRow, 0).toString();
            //            System.out.println("ID is " + i);

            data = new TaskClass();
            data.setId(Integer.parseInt(dtm.getValueAt(selectedRow, 0).toString()));
            data.setTitle(dtm.getValueAt(selectedRow, 1).toString());
            data.setDescription(dtm.getValueAt(selectedRow, 2).toString());
//            String role = dtm.getValueAt(selectedRow, 3).toString();
//            if (role.equals("Admin")) {
//                data.setRole(1);
//            } else if (role.equals("Manager")) {
//                data.setRole(2);
//            } else if (role.equals("Employee")) {
//                data.setRole(3);
//            }
            data.setStratDate(dtm.getValueAt(selectedRow, 3).toString());
            data.setDueDate(dtm.getValueAt(selectedRow, 4).toString());
            if(!"Pending".equals(dtm.getValueAt(selectedRow, 3).toString()))data.setStatus(1);
            //            data.setStatus();
            //
            else {
                data.setStatus(0);
            }

            String sql = "SELECT * FROM tasks WHERE ID=? ";
            PreparedStatement ps = connectionClass.connection.prepareStatement(sql);
            ps.setInt(1, data.getId());
            //            ps.setInt(2, 1);

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                data.setEmployeeId(rs.getInt("employeeID"));
                data.setManagerId(rs.getInt("managerId"));
//                data.setPassword(rs.getString("password"));
//                data.setContactNumber(rs.getString("contactNumber"));
                //                data.setAdharNumber(rs.getString("adharNumber"));

            }
            AssignTask employee = new AssignTask( data , ManagerData );
            employee.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(UsersTAble.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
  switch (role) {
            case 1 -> {
                AdminPanel admin = new AdminPanel(ManagerData);
                admin.setVisible(true);
                this.dispose();
            }
            case 2 -> {
                ManagerPanel manager = new ManagerPanel(ManagerData);
                manager.setVisible(true);
                this.dispose();
            }
            default -> {
                EmployeePanel manager = new EmployeePanel(ManagerData);
                manager.setVisible(true);
                this.dispose();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
 StatusTable status = new StatusTable(ManagerData, 1);
        status.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
 StatusTable status = new StatusTable(ManagerData, 0);
        status.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.task_management.Button button1;
    private com.mycompany.task_management.Button button2;
    private com.mycompany.task_management.Button button3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.mycompany.task_management.TableDark table;
    // End of variables declaration//GEN-END:variables

    public void createTable() {
        if (role == 1) {
            String statement = "SELECT * FROM tasks";

            try {
                PreparedStatement ps = connectionClass.connection.prepareStatement(statement);
                ResultSet resultSet = ps.executeQuery();

                String[] headerName = {"ID", "Title", "Description", "Start Date", "Due Date", "Status"};
                DefaultTableModel model = new DefaultTableModel(null, headerName);
                table.setModel(model);

                while (resultSet.next()) {
                    TaskClass data = new TaskClass();
                    data.setId(resultSet.getInt("ID"));
                    data.setTitle(resultSet.getString("title"));
                    data.setDescription(resultSet.getString("description"));
                    data.setStatus(resultSet.getInt("status"));
                    data.setStratDate(resultSet.getString("startDate"));
                    data.setDueDate(resultSet.getString("dueDate"));

                    taskdata.add(data);
                }

                Object[] row = new Object[6];
                for (int i = 0; i < taskdata.size(); i++) {
                    row[0] = taskdata.get(i).getId();
                    row[1] = taskdata.get(i).getTitle();
                    row[2] = taskdata.get(i).getDescription();
                    row[3] = taskdata.get(i).getStratDate();
                    row[4] = taskdata.get(i).getDueDate();

                    if (taskdata.get(i).getStatus() == 0) {
                        row[5] = "Pending";
                    } else {
                        row[5] = "Completed";
                    }
                    model.addRow(row);
                }
            } catch (SQLException ex) {
                Logger.getLogger(TaskTable.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            String statement = "SELECT * FROM tasks WHERE managerID =?";

            try {
                PreparedStatement ps = connectionClass.connection.prepareStatement(statement);
                ps.setInt(1, ManagerData.getId());
                ResultSet resultSet = ps.executeQuery();

                String[] headerName = {"ID", "Title", "Description", "Start Date", "Due Date","Status"};
                DefaultTableModel model = new DefaultTableModel(null, headerName);
                table.setModel(model);

                while (resultSet.next()) {
                    TaskClass data = new TaskClass();
                    data.setId(resultSet.getInt("ID"));
                    data.setTitle(resultSet.getString("title"));
                    data.setDescription(resultSet.getString("description"));
                    data.setStatus(resultSet.getInt("status"));
                    data.setStratDate(resultSet.getString("startDate"));
                    data.setDueDate(resultSet.getString("dueDate"));
                    taskdata.add(data);
                }

                Object[] row = new Object[6];
                for (int i = 0; i < taskdata.size(); i++) {
                    row[0] = taskdata.get(i).getId();
                    row[1] = taskdata.get(i).getTitle();
                    row[2] = taskdata.get(i).getDescription();
                    row[3] = taskdata.get(i).getStratDate();
                    row[4] = taskdata.get(i).getDueDate();

                    if (taskdata.get(i).getStatus() == 0) {
                        row[5] = "Pending";
                    } else {
                        row[5] = "Completed";
                    }
                    model.addRow(row);
                }
            } catch (SQLException ex) {
                Logger.getLogger(TaskTable.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    public void createAssignTable() {
        String statement = "SELECT * FROM tasks WHERE employeeID =?";

        try {
            PreparedStatement ps = connectionClass.connection.prepareStatement(statement);
            ps.setInt(1, ManagerData.getId());
            ResultSet resultSet = ps.executeQuery();

            String[] headerName = {"ID", "Title", "Description", "Start Date", "Due Date","Status"};
            DefaultTableModel model = new DefaultTableModel(null, headerName);
            table.setModel(model);

            while (resultSet.next()) {
                TaskClass data = new TaskClass();
                data.setId(resultSet.getInt("ID"));
                data.setTitle(resultSet.getString("title"));
                data.setDescription(resultSet.getString("description"));
                data.setStatus(resultSet.getInt("status"));
                data.setStratDate(resultSet.getString("startDate"));
                data.setDueDate(resultSet.getString("dueDate"));
                taskdata.add(data);
            }

            Object[] row = new Object[6];
            for (int i = 0; i < taskdata.size(); i++) {
                row[0] = taskdata.get(i).getId();
                row[1] = taskdata.get(i).getTitle();
                row[2] = taskdata.get(i).getDescription();
                row[3] = taskdata.get(i).getStratDate();
                row[4] = taskdata.get(i).getDueDate();

                if (taskdata.get(i).getStatus() == 0) {
                    row[5] = "Pending";
                } else {
                    row[5] = "Completed";
                }
                model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TaskTable.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
